# Site settings
encoding: utf-8
lang: en-US
title: "Your title"
author: "Your name"
email: "your-email@domain.com"
description: >
  A description for your page.
url: "https://areebk.gitlab.io"
baseurl: "/kiko-minus"
nav:
  - name: "About"
    url: "/about"
  - name: "Archive"
    url: "/archive"
copyright:
  year: 2019
  name: "Your Name"

# Excludes
exclude:
  - README.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - kiko-minus.gemspec
  - .gitignore
  - .gitlab-ci.yml
  - .jekyll-cache

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Gem settings
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
twitter:
  username: "mytwitter"
author: "mytwitter"
social:
  name: "Your Name"
  links:
    - https://twitter.com/YourTwitter
    - https://www.facebook.com/YourFacebook
    - https://www.linkedin.com/in/YourLinkedin
    - https://github.com/YourGithub

# Jekyll settings
sass:
  style: compressed
permalink: pretty
timezone: America/Los_Angeles
