# Site settings
encoding: utf-8
lang: en-US
title: "Your title"
# logo: "/assets/logos/logo.svg"
author: "Your name"
email: "your-email@domain.com"
description: >
  A description for your page.
baseurl: ""
url: ""
nav:
  - name: "About"
    url: "/about"
  - name: "Archive"
    url: "/archive"
copyright:
  year: 2019
  name: Your Name

# Excludes
exclude:
  - README.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - kiko-minus.gemspec
  - .gitignore
  - .jekyll-cache

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Gem settings
pagination:
  enabled: true
  per_page: 2
  permalink: "/page/:num/"
  title: ":title - page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
twitter:
  username: mytwitter
author: mytwitter
social:
  name: Your Name
  links:
    - https://twitter.com/YourTwitter
    - https://www.facebook.com/YourFacebook
    - https://www.linkedin.com/in/YourLinkedin
    - https://github.com/YourGithub

# Jekyll settings
sass:
  style: compressed
permalink: pretty
timezone: America/Los_Angeles

# Favicons
# favicons:
#   16: "/assets/logos/logo@16px.png"
#   32: "/assets/logos/logo@32px.png"
#   96: "/assets/logos/logo@96px.png"
#   120: "/assets/logos/logo@120px.png"
#   144: "/assets/logos/logo@144px.png"
#   180: "/assets/logos/logo@180px.png"
#   512: "/assets/logos/logo@512px.png"
#   1024: "/assets/logos/logo@1024px.png"
